# Generated by Django 5.1.2 on 2024-10-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('idTrajet', models.AutoField(primary_key=True, serialize=False)),
                ('pointDepart', models.CharField(max_length=255)),
                ('pointArrive', models.CharField(max_length=255)),
            ],
        ),
    ]
