# Generated by Django 5.1.2 on 2024-10-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_trajet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='pointArrive',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='pointDepart',
            field=models.CharField(max_length=100),
        ),
    ]
