# Generated by Django 5.1.2 on 2024-11-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_trajet_pointarrive_alter_trajet_pointdepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('idBus', models.AutoField(primary_key=True, serialize=False)),
                ('numLigne', models.CharField(max_length=100)),
            ],
        ),
    ]
