# Generated by Django 5.1.2 on 2024-11-03 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0005_conduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatBusTrajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.bus')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.trajet')),
            ],
        ),
    ]
